// kc-react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import { DeliveryClient } from 'kentico-cloud-delivery';

const client = new DeliveryClient({ projectId: "975bf280-fd91-488c-994c-2f04416e5ee3" });

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      loaded: false,
      articles: []
    };
  }

  componentDidMount() {
    client.items()
      .type("article")
      .getPromise()
      .then(result => {
        console.log(result.items);
        this.setState({
          loaded: true,
          articles: result.items
        });
      })
  }


  render() {
    const articles = this.state.articles.map(article => (<li>{article.elements.title.value}</li>));
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          {this.state.loaded && (<ul>{articles}</ul>)}
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App;

// kc-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

import { DeliveryClient, IDeliveryClient, ContentItem } from 'kentico-cloud-delivery';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  client: IDeliveryClient;
  articles: ContentItem[];
  loaded: boolean;
  title = 'kc-angular';

  constructor() {
    this.client = new DeliveryClient({ projectId: '975bf280-fd91-488c-994c-2f04416e5ee3' });
    this.loaded = false;
    this.articles = [];
  }

  ngOnInit(): void {
    this.client.items()
      .type('article')
      .getPromise()
      .then(result => {
        // eslint-disable-next-line no-console
        console.log(result.items);
        this.articles = result.items;
        this.loaded = true;
      });
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<section *ngIf="loaded">
  <ul *ngFor="let article of articles">
    <li>{{article.elements.title.value}}</li>
  </ul>
</section>
<h2>Here are some links to help you start: </h2>
<ul>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://angular.io/tutorial">Tour of Heroes</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://angular.io/cli">CLI Documentation</a></h2>
  </li>
  <li>
    <h2><a target="_blank" rel="noopener" href="https://blog.angular.io/">Angular blog</a></h2>
  </li>
</ul>
